version: '3'

services:
  wordpress:
    image: wordpress:latest
    ports:
      - 8081:80
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_SMTP_HOST: mailhog
      WORDPRESS_SMTP_PORT: 1025
    volumes:
      - wp_data:/var/www/html

  db:
    image: mysql:latest
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:80

  mailhog:
    image: mailhog/mailhog
    ports:
      - 8025:8025

  flask-app:
    build:
      context: ./flask
      dockerfile: Dockerfile
    ports:
      - 5001:5000
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 8000:3000
    restart: always

volumes:
  wp_data:
  db_data:
